baseurl = "/"
languageCode = "en-us"
title = "ReadAILib Official Website "
theme = "hugo-lithium-theme"
googleAnalytics = "UA-111305334-1"
disqusShortname = "readailib"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/readailib"
[[menu.main]]
    name = "YouTube"
    url = "https://www.youtube.com/channel/UCTOuJy4b9E89zCwffX-qC3A"

[params]
    description = "ReadAILib Official Website."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml","Dockerfile","python"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

